---
# Separate the workflow for actionlint to other workflows, because if a workflow for actionlint is broken actionlint isn't run
name: actionlint
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - aqua/imports/actionlint.yaml
      - aqua/imports/reviewdog.yaml
jobs:
  actionlint:
    uses: suzuki-shunsuke/actionlint-workflow/.github/workflows/actionlint.yaml@v1.0.0
    with:
      aqua_version: v2.25.1
      aqua_policy_allow: true
    permissions:
      pull-requests: write
      contents: read
