---
name: go-mod-tidy
on: workflow_call
jobs:
  go-mod-tidy:
    uses: suzuki-shunsuke/go-mod-tidy-workflow/.github/workflows/go-mod-tidy.yaml@8facac38f5b2008648c14e31c632c3a709439b9c # v0.1.1
    with:
      go-version: 1.20.4
      aqua_version: v2.7.0
    secrets:
      gh_app_id: ${{secrets.APP_ID_AQUAPROJ_AQUA}}
      gh_private_key: ${{secrets.APP_PRIVATE_KEY_AQUAPROJ_AQUA}}
    permissions:
      contents: read
